/* Template for js/config.js — generated by build.js from .env.
   Do not edit js/config.js by hand; edit .env and rebuild. */
window.ENZO_CONFIG = {
  formspreeId: '' // falls back to WhatsApp when empty
};
