const fs   = require('fs');
const path = require('path');

function copyDir(src, dest) {
  if (!fs.existsSync(src)) return;
  fs.mkdirSync(dest, { recursive: true });
  fs.readdirSync(src).forEach(function (file) {
    var s = path.join(src, file);
    var d = path.join(dest, file);
    fs.statSync(s).isDirectory() ? copyDir(s, d) : fs.copyFileSync(s, d);
  });
}

// ── Read .env (optional) → KEY=VALUE map ──
function loadEnv() {
  var env = {};
  try {
    fs.readFileSync('.env', 'utf8').split(/\r?\n/).forEach(function (line) {
      line = line.trim();
      if (!line || line[0] === '#') return;
      var i = line.indexOf('=');
      if (i === -1) return;
      env[line.slice(0, i).trim()] = line.slice(i + 1).trim();
    });
  } catch (e) { /* no .env present — fine, values default to empty */ }
  return env;
}

// ── Generate client config (js/config.js) from .env ──
// The Formspree ID is public by design (visible in the network request); this
// keeps it out of source control and in one place, not a security boundary.
var env = loadEnv();
var configJs =
  '/* AUTO-GENERATED by build.js from .env — do not edit by hand. */\n' +
  'window.ENZO_CONFIG = {\n' +
  '  formspreeId: ' + JSON.stringify(env.FORMSPREE_ID || '') + '\n' +
  '};\n';
fs.writeFileSync('js/config.js', configJs);
console.log('generated → js/config.js');

// ── Build dist/ (nav + footer are inlined in each page; no injection step) ──
var pages = ['index', 'about', 'catalog', 'calculator', 'contact'];

// Clean dist so removed source files never linger in the artifact.
// rmSync can hit EPERM on Windows if a file is briefly locked — retry, then
// fall back to best-effort so the build still produces an up-to-date artifact.
try {
  fs.rmSync('dist', { recursive: true, force: true, maxRetries: 5, retryDelay: 120 });
} catch (e) {
  console.warn('warning: could not fully clean dist/ (' + e.code + ') — continuing');
}
fs.mkdirSync('dist', { recursive: true });

pages.forEach(function (page) {
  fs.copyFileSync(page + '.html', 'dist/' + page + '.html');
  console.log('copied → dist/' + page + '.html');
});

copyDir('assets', 'dist/assets');
copyDir('js',     'dist/js');   // includes the generated config.js
copyDir('data',   'dist/data');

['robots.txt', 'sitemap.xml'].forEach(function (f) {
  if (fs.existsSync(f)) fs.copyFileSync(f, 'dist/' + f);
});
console.log('copied → assets/ js/ data/ + SEO files');
